"""empty message

Revision ID: 8120325d8973
Revises: 884e8920f29d
Create Date: 2021-08-19 11:16:23.086894

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8120325d8973'
down_revision = '884e8920f29d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tmahasiswa', 'nohp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tmahasiswa', sa.Column('nohp', mysql.VARCHAR(length=200), nullable=False))
    # ### end Alembic commands ###
